/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CurriculumContract } from "./CurriculumContract";
export type { DegreeToken } from "./DegreeToken";
export type { UniversityContract } from "./UniversityContract";
