/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UniversityContractInterface extends Interface {
  getFunction(
    nameOrSignature: "addACurriculum" | "curriculums" | "universityInfo"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CurriculumAdded"): EventFragment;

  encodeFunctionData(
    functionFragment: "addACurriculum",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "curriculums",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "universityInfo",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addACurriculum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "curriculums",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "universityInfo",
    data: BytesLike
  ): Result;
}

export namespace CurriculumAddedEvent {
  export type InputTuple = [curriculumAddress: AddressLike];
  export type OutputTuple = [curriculumAddress: string];
  export interface OutputObject {
    curriculumAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniversityContract extends BaseContract {
  connect(runner?: ContractRunner | null): UniversityContract;
  waitForDeployment(): Promise<this>;

  interface: UniversityContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addACurriculum: TypedContractMethod<
    [curAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  curriculums: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  universityInfo: TypedContractMethod<
    [],
    [
      [string, string, boolean] & {
        uniAdress: string;
        name: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addACurriculum"
  ): TypedContractMethod<[curAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "curriculums"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "universityInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, boolean] & {
        uniAdress: string;
        name: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CurriculumAdded"
  ): TypedContractEvent<
    CurriculumAddedEvent.InputTuple,
    CurriculumAddedEvent.OutputTuple,
    CurriculumAddedEvent.OutputObject
  >;

  filters: {
    "CurriculumAdded(address)": TypedContractEvent<
      CurriculumAddedEvent.InputTuple,
      CurriculumAddedEvent.OutputTuple,
      CurriculumAddedEvent.OutputObject
    >;
    CurriculumAdded: TypedContractEvent<
      CurriculumAddedEvent.InputTuple,
      CurriculumAddedEvent.OutputTuple,
      CurriculumAddedEvent.OutputObject
    >;
  };
}
