/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CurriculumContract__factory } from "./CurriculumContract__factory";
export { DegreeToken__factory } from "./DegreeToken__factory";
export { UniversityContract__factory } from "./UniversityContract__factory";
